POST http://127.0.0.1:8000/api/accounts/upload-resume/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY5NjQ0MjMwLCJpYXQiOjE3Njk2NDMzMzAsImp0aSI6IjliZWUwNTAzYTAwMTQwMzA5OTUwMjhiNzdhNTVkMDEwIiwidXNlcl9pZCI6IjQifQ.WbnSc2ZhUTKoMxTex6Cg4_FM8Iw2L4b3wnNoywjkIwI
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="activity-11.pdf"
Content-Type: application/pdf

< ./activity-11.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--
